<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InformasiPublikSeeder extends Seeder
{
    /**
     * Seed 20 informasi publik dengan berbagai kategori dan tahun.
     */
    public function run(): void
    {
        $informasiPublik = [
            [
                'judul' => 'Laporan Tahunan Pengadilan Agama Penajam 2024',
                'kategori' => 'berkala',
                'sub_kategori' => 'Laporan Tahunan',
                'deskripsi' => 'Laporan kinerja tahunan Pengadilan Agama Penajam tahun 2024 yang mencakup data perkara, capaian kinerja, dan rencana strategis.',
                'file_path' => 'uploads/informasi_publik/laporan-tahunan-2024.pdf',
                'tahun' => 2024,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2024-03-15 08:00:00',
            ],
            [
                'judul' => 'Laporan Tahunan Pengadilan Agama Penajam 2023',
                'kategori' => 'berkala',
                'sub_kategori' => 'Laporan Tahunan',
                'deskripsi' => 'Laporan kinerja tahunan Pengadilan Agama Penajam tahun 2023.',
                'file_path' => 'uploads/informasi_publik/laporan-tahunan-2023.pdf',
                'tahun' => 2023,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2023-03-10 08:00:00',
            ],
            [
                'judul' => 'Laporan Keuangan Semester I Tahun 2024',
                'kategori' => 'berkala',
                'sub_kategori' => 'Laporan Keuangan',
                'deskripsi' => 'Laporan penggunaan anggaran semester pertama tahun 2024.',
                'file_path' => 'uploads/informasi_publik/lapkeu-semester1-2024.pdf',
                'tahun' => 2024,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2024-07-20 09:00:00',
            ],
            [
                'judul' => 'Laporan Keuangan Semester II Tahun 2023',
                'kategori' => 'berkala',
                'sub_kategori' => 'Laporan Keuangan',
                'deskripsi' => 'Laporan penggunaan anggaran semester kedua tahun 2023.',
                'file_path' => 'uploads/informasi_publik/lapkeu-semester2-2023.pdf',
                'tahun' => 2023,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2024-01-15 09:00:00',
            ],
            [
                'judul' => 'Statistik Perkara Tahun 2024',
                'kategori' => 'berkala',
                'sub_kategori' => 'Statistik Perkara',
                'deskripsi' => 'Data statistik perkara yang diterima dan diputus Pengadilan Agama Penajam tahun 2024.',
                'file_path' => 'uploads/informasi_publik/statistik-perkara-2024.pdf',
                'tahun' => 2024,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2024-12-30 10:00:00',
            ],
            [
                'judul' => 'Statistik Perkara Tahun 2022',
                'kategori' => 'berkala',
                'sub_kategori' => 'Statistik Perkara',
                'deskripsi' => 'Data statistik perkara yang diterima dan diputus Pengadilan Agama Penajam tahun 2022.',
                'file_path' => 'uploads/informasi_publik/statistik-perkara-2022.pdf',
                'tahun' => 2022,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2023-01-10 10:00:00',
            ],
            [
                'judul' => 'Pengumuman Sidang Keliling Bulan Januari 2025',
                'kategori' => 'serta_merta',
                'sub_kategori' => 'Pengumuman Sidang',
                'deskripsi' => 'Jadwal dan lokasi pelaksanaan sidang keliling Pengadilan Agama Penajam bulan Januari 2025.',
                'file_path' => 'uploads/informasi_publik/sidang-keliling-jan-2025.pdf',
                'tahun' => 2025,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2025-01-02 08:00:00',
            ],
            [
                'judul' => 'Pengumuman Libur Nasional dan Cuti Bersama 2025',
                'kategori' => 'serta_merta',
                'sub_kategori' => 'Pengumuman',
                'deskripsi' => 'Informasi hari libur nasional dan cuti bersama Pengadilan Agama Penajam tahun 2025.',
                'file_path' => 'uploads/informasi_publik/libur-nasional-2025.pdf',
                'tahun' => 2025,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2025-01-05 08:00:00',
            ],
            [
                'judul' => 'Maklumat Pelayanan Pengadilan Agama Penajam',
                'kategori' => 'serta_merta',
                'sub_kategori' => 'Maklumat',
                'deskripsi' => 'Maklumat pelayanan publik Pengadilan Agama Penajam yang berlaku efektif.',
                'file_path' => 'uploads/informasi_publik/maklumat-pelayanan.pdf',
                'tahun' => 2024,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2024-06-01 08:00:00',
            ],
            [
                'judul' => 'Pengumuman Seleksi CPNS 2024',
                'kategori' => 'serta_merta',
                'sub_kategori' => 'Pengumuman',
                'deskripsi' => 'Pengumuman terkait seleksi penerimaan CPNS di lingkungan Pengadilan Agama Penajam tahun 2024.',
                'file_path' => 'uploads/informasi_publik/seleksi-cpns-2024.pdf',
                'tahun' => 2024,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2024-09-01 08:00:00',
            ],
            [
                'judul' => 'Prosedur Pendaftaran Perkara Online',
                'kategori' => 'setiap_saat',
                'sub_kategori' => 'Prosedur',
                'deskripsi' => 'Panduan lengkap tata cara pendaftaran perkara secara online melalui e-Court.',
                'file_path' => 'uploads/informasi_publik/prosedur-ecourt.pdf',
                'tahun' => 2024,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2024-02-01 08:00:00',
            ],
            [
                'judul' => 'Prosedur Pengajuan Gugatan Cerai',
                'kategori' => 'setiap_saat',
                'sub_kategori' => 'Prosedur',
                'deskripsi' => 'Panduan lengkap persyaratan dan prosedur pengajuan gugatan cerai di Pengadilan Agama Penajam.',
                'file_path' => 'uploads/informasi_publik/prosedur-cerai.pdf',
                'tahun' => 2023,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2023-05-15 08:00:00',
            ],
            [
                'judul' => 'Tarif Biaya Perkara Pengadilan Agama',
                'kategori' => 'setiap_saat',
                'sub_kategori' => 'Tarif',
                'deskripsi' => 'Daftar biaya perkara yang berlaku di Pengadilan Agama Penajam sesuai SK Ketua Mahkamah Agung.',
                'file_path' => 'uploads/informasi_publik/tarif-biaya-perkara.pdf',
                'tahun' => 2024,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2024-01-02 08:00:00',
            ],
            [
                'judul' => 'Struktur Organisasi Pengadilan Agama Penajam',
                'kategori' => 'setiap_saat',
                'sub_kategori' => 'Profil',
                'deskripsi' => 'Bagan struktur organisasi dan pejabat Pengadilan Agama Penajam.',
                'file_path' => 'uploads/informasi_publik/struktur-organisasi.pdf',
                'tahun' => 2024,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2024-01-10 08:00:00',
            ],
            [
                'judul' => 'Visi Misi Pengadilan Agama Penajam',
                'kategori' => 'setiap_saat',
                'sub_kategori' => 'Profil',
                'deskripsi' => 'Visi, misi, dan tujuan strategis Pengadilan Agama Penajam.',
                'file_path' => 'uploads/informasi_publik/visi-misi.pdf',
                'tahun' => 2023,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2023-01-05 08:00:00',
            ],
            [
                'judul' => 'SOP Pelayanan Informasi Publik',
                'kategori' => 'setiap_saat',
                'sub_kategori' => 'SOP',
                'deskripsi' => 'Standar Operasional Prosedur pelayanan informasi publik melalui PPID Pengadilan Agama Penajam.',
                'file_path' => 'uploads/informasi_publik/sop-ppid.pdf',
                'tahun' => 2024,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2024-04-01 08:00:00',
            ],
            [
                'judul' => 'Putusan Perkara No. 123/Pdt.G/2024/PA.Pnj',
                'kategori' => 'setiap_saat',
                'sub_kategori' => 'Putusan',
                'deskripsi' => 'Salinan putusan perkara gugatan cerai nomor 123/Pdt.G/2024/PA.Pnj.',
                'file_path' => 'uploads/informasi_publik/putusan-123-2024.pdf',
                'tahun' => 2024,
                'nomor_perkara' => '123/Pdt.G/2024/PA.Pnj',
                'is_published' => true,
                'published_at' => '2024-08-20 10:00:00',
            ],
            [
                'judul' => 'Putusan Perkara No. 45/Pdt.G/2023/PA.Pnj',
                'kategori' => 'setiap_saat',
                'sub_kategori' => 'Putusan',
                'deskripsi' => 'Salinan putusan perkara gugatan cerai nomor 45/Pdt.G/2023/PA.Pnj.',
                'file_path' => 'uploads/informasi_publik/putusan-45-2023.pdf',
                'tahun' => 2023,
                'nomor_perkara' => '45/Pdt.G/2023/PA.Pnj',
                'is_published' => true,
                'published_at' => '2023-06-15 10:00:00',
            ],
            [
                'judul' => 'Rencana Kerja Anggaran 2025',
                'kategori' => 'berkala',
                'sub_kategori' => 'Anggaran',
                'deskripsi' => 'Rencana kerja dan anggaran Pengadilan Agama Penajam untuk tahun anggaran 2025.',
                'file_path' => 'uploads/informasi_publik/rka-2025.pdf',
                'tahun' => 2025,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2025-01-15 08:00:00',
            ],
            [
                'judul' => 'Laporan Indeks Kepuasan Masyarakat 2024',
                'kategori' => 'berkala',
                'sub_kategori' => 'Survei',
                'deskripsi' => 'Hasil survei Indeks Kepuasan Masyarakat terhadap pelayanan Pengadilan Agama Penajam tahun 2024.',
                'file_path' => 'uploads/informasi_publik/ikm-2024.pdf',
                'tahun' => 2024,
                'nomor_perkara' => null,
                'is_published' => true,
                'published_at' => '2024-12-20 09:00:00',
            ],
        ];

        $now = now();

        foreach ($informasiPublik as $info) {
            DB::table('informasi_publik')->insert(array_merge($info, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }
    }
}
